name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '8.0.x'
        cache: true
        cache-dependency-path: "AlgorithmsAndDataStructures.sln"

    - name: Restore dependencies
      run: dotnet restore "AlgorithmsAndDataStructures.sln"

    - name: Build project
      run: dotnet build --no-restore --configuration Release "AlgorithmsAndDataStructures.sln"

    - name: Run tests
      run: dotnet test --no-build --verbosity normal --configuration Release "AlgorithmsAndDataStructures.sln"

    - name: Install Google Test
      run: sudo apt-get update && sudo apt-get install -y libgtest-dev

    - name: Build C++ projects
      run: |
           make -C "src/MyDataStructures/MyDataStructuresOnCpp"
           make -C "src/DemonstrationOfSoftware/DemonstrationOfSoftwareOnCpp"

    - name: Test C++ projects
      run: |
           make -C "src/MyDataStructures/MyDataStructuresOnCpp" test
           cd src/MyDataStructures/MyDataStructuresOnCpp/ 
           ./run_tests